language: csharp
solution: FiratBank.sln
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet build ./Domain/
  - dotnet build ./Domain.Tests/
  - dotnet test ./Domain.Tests/Domain.Tests.csproj /p:CollectCoverage=true
